<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="BTP152883" name="runners.TestRunner" tests="5" failures="5" timestamp="04 Nov 2018 14:21:07 GMT" time="39.158" errors="0">
  <testcase name="runScenario" time="21.010" classname="runners.TestRunner">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:568)at org.testng.Assert.assertEquals(Assert.java:578)at stepDefinitions.LoginSteps.user_maybe_be_navigated_to_the_homepage(LoginSteps.java:68)at ✽.user should be navigated to the homepage(src/test/resources/functionalTests/login.feature:30)]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="4.581" classname="runners.TestRunner">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:568)at org.testng.Assert.assertEquals(Assert.java:578)at stepDefinitions.LoginSteps.user_maybe_be_navigated_to_the_homepage(LoginSteps.java:68)at ✽.user should not be navigated to the homepage(src/test/resources/functionalTests/login.feature:37)]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="4.630" classname="runners.TestRunner">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:568)at org.testng.Assert.assertEquals(Assert.java:578)at stepDefinitions.LoginSteps.user_maybe_be_navigated_to_the_homepage(LoginSteps.java:68)at ✽.user should be navigated to the homepage(src/test/resources/functionalTests/login.feature:37)]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="4.128" classname="runners.TestRunner">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:568)at org.testng.Assert.assertEquals(Assert.java:578)at stepDefinitions.LoginSteps.user_maybe_be_navigated_to_the_homepage(LoginSteps.java:68)at ✽.user should not be navigated to the homepage(src/test/resources/functionalTests/login.feature:37)]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="4.809" classname="runners.TestRunner">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:568)at org.testng.Assert.assertEquals(Assert.java:578)at stepDefinitions.LoginSteps.user_maybe_be_navigated_to_the_homepage(LoginSteps.java:68)at ✽.user should not be navigated to the homepage(src/test/resources/functionalTests/login.feature:37)]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- runners.TestRunner -->
